# Generated by Django 5.1.2 on 2025-12-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_user_options'),
        ('payment', '0008_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма платежа в рублях'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.currency', verbose_name='Валюта транспорта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость доставки в рублях'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Курс на момент создания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа (в валюте транспорта)'),
        ),
    ]
