# Generated by Django 5.0.6 on 2025-12-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0011_add_city_coordinates'),
        ('franchise', '0011_city_country_currency'),
    ]

    operations = [
    ]
