# Generated by Django 5.0.2 on 2024-12-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_requestrent_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrent',
            name='status',
            field=models.CharField(choices=[('accept', 'Принять'), ('denied', 'Отказать'), ('unknown', 'Не рассмотрено'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='unknown', max_length=8, verbose_name='Статус'),
        ),
    ]
