# Generated by Django 5.0.6 on 2026-01-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_fix_thai_baht_currency'),
        ('app', '0028_populate_currency_symbols'),
    ]

    operations = [
    ]
