# Generated by Django 5.0.6 on 2026-01-25 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_merge_20260125_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='LessorWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('denied', 'Отказано')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('denied_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина отказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='app.lessor', verbose_name='Арендодатель')),
            ],
            options={
                'verbose_name': 'Заявка на вывод средств (арендодатель)',
                'verbose_name_plural': 'Заявки на вывод средств (арендодатели)',
                'ordering': ['-created_at'],
            },
        ),
    ]
