# Generated by Django 5.0.6 on 2025-12-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0034_vehicle_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='rentprice',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='ИТОГО'),
        ),
    ]
